### ISSUE TITLE
Win32 exeption

### ISSUE THREAD

**Issue by visign3d** [ReactUnity/core#1]
Got this exeption by opening setup wizard:
Win32Exception: ApplicationName='node', CommandLine='-v', CurrentDirectory='', Native error= The system cannot find the file specified. Node.js is installed.

**Comment by KurtGokhan** [comment]
If node is installed but you are getting this error, node may not be in the PATH. I will try to handle this gracefully.

I am aware that Quick Start wizard is under-developed right now. It will do more useful things in the future but right now only thing it does is:

- Run `npm init react-unity` from project root. This will create a npm project in `react` folder in project root with dependencies set up.

So for now please do this manually if the setup wizard does not work for you.

**Comment by visign3d** [comment]
Thank. Is it possible use Material UI ?

**Comment by KurtGokhan** [comment]
It is not possible to use Material UI. It is DOM based and this package does not support DOM. Think of this package as React Native, but for Unity.

Which features of Material UI are you interested in?

**Comment by visign3d** [comment]
Well, everything UI - scrolls,buttons,toggels,tables etc.
