### ISSUE TITLE
TS2339: Property 'scroll' does not exist on type 'JSX.IntrinsicElements'

### ISSUE THREAD

**Issue by tmyroadctfig** [ReactUnity/core#107]
I bumped from v0.15.x to v0.18.0 to see whether that would help with #106, and now typescript doesn't seem to recognise the `<scroll>` element.

```
TS2339: Property 'scroll' does not exist on type 'JSX.IntrinsicElements'.
    18 |     <div className='root'>
    19 |       <h1>Heading</h1>
  > 20 |       <scroll>
```

**Comment by KurtGokhan** [comment]
Seems like a Typescript setup issue. Let's continue the discussion on #106
