### ISSUE TITLE
Open to work?

### ISSUE THREAD

**Issue by rocco-haro** [ReactUnity/core#11]
Hello @KurtGokhan ,

I'm running a bootstrapped startup that would very much like to engage with your code base. Are you open to relaxed, part-time work? 

If so, please feel free to drop me an email at rocco@kickback.space

Thanks for the consideration.

**Comment by rocco-haro** [comment]
@KurtGokhan

**Comment by KurtGokhan** [comment]
My personal email is public now. Anyone can contact me at krtgkn@gmail.com
