### ISSUE TITLE
Upgrade Support for newest Unity LTS 2022+

### ISSUE THREAD

**Issue by SinhtUp** [ReactUnity/core#110]
The Unity version Support is outdated,
i cant use the package for the actual LTS version.
May you can recompile it for the newest LTS Versions?

Tesekkürler.

**Comment by SinhtUp** [comment]
i also have seen that your test in edit mode for the 2022 version of the unity image fails may the cause is that the newer verrsion uses a different validation style for your license, ive had problems with my gitlab ci too.

**Comment by KurtGokhan** [comment]
I see that it works in 2022. The reason full-sample project doesn't work is because it was opened in 2023 and its packages weren't compatible with 2022. Is there another issue you are encountering with 2022?

**Comment by SinhtUp** [comment]
i'am following your readme to setup the package in my Project, the import and everything works fine but as soon as i try to add the react Canvas to my active scene, which inherits the ReactRenderer Component it seems like my editor cannot find the path of the script, as soon as i run Play in Edit mode it tries to resolve the ref path.
the importet package lays in /Packages/React Unity as it should be the scripts and everything is there but i cant add them to my GameObjects as a Component.

**Comment by KurtGokhan** [comment]
Can you add some screenshots to show what exactly doesn't work?

Make sure the script exists in that path. If it doesn't exist, you may have not built your React project yet. You can also try the dev server first to see if ReactUnity is working at all.

**Comment by SinhtUp** [comment]
never mind looks like i have to edit the path to the actual React environment i have set up, everything works fine know.
