### ISSUE TITLE
[BUG] Images are loaded incorrectly in production

### ISSUE THREAD

**Issue by xiaohai-huang** [ReactUnity/core#113]
## Description
Images load correctly during development, but when the React app is served from the __Resources__ folder, incorrect images are displayed due to identical file names with different extensions.

## Steps to Reproduce

1. Import two images with identical file names but different file extensions from separate folders.

```js
import PlaceholderAvatar from "src/assets/images/icons/default-avatar.png";
import PlayerAvatar from "src/assets/images/default-avatar.jpg";
```
2. Build the react app. Below shows the files are all stored under __/static/media/__ folder.
![image](https://github.com/user-attachments/assets/ad92a59d-b809-4cfd-a29f-582b7d844b46)

3. `ResourcesHelper.LoadResource` is unable to load the correct image.

## Potential Cause
Currently, the files in __Resources__ folder are loaded without file extension.

https://github.com/ReactUnity/core/blob/fef8c873b41af0922c3cffe6e98d37dc0efee34f/Runtime/Types/AssetReference.cs#L168-L188

https://github.com/ReactUnity/core/blob/fef8c873b41af0922c3cffe6e98d37dc0efee34f/Runtime/Helpers/ResourcesHelper.cs#L55-L63

**Comment by xiaohai-huang** [comment]
My current workaround is to either change the file names or specify the `assetModuleFilename` in webpack config using __webpack-merge__.

```js
{    
   output: {
      assetModuleFilename: "static/media/[name].[hash][ext]",
    }
}
```

**Comment by KurtGokhan** [comment]
In the new version of `@reactunity/scripts` package, extension names will be added to the end of the file names to avoid name collisions, because Unity ignores extensions in Resources.
