### ISSUE TITLE
[Request] CodePush feature

### ISSUE THREAD

**Issue by isrmicha** [ReactUnity/core#114]
Hello o/
Any plans on some kind of CodePush feature for this lib?

https://github.com/microsoft/react-native-code-push

**Comment by KurtGokhan** [comment]
This is not planned in a foreseeable future. Right now ReactUnity supports loading script source and images from web addresses, much like web browsers. So it doesn't need a code-push service like React Native does. Users can add their own implementation of code-push services if they really need it.
