### ISSUE TITLE
[CSS] The backdrop-filter: blur property don't work and box-shadow doesn't work well

### ISSUE THREAD

**Issue by ds199895** [ReactUnity/core#115]

**Comment by ds199895** [comment]
![图片](https://github.com/user-attachments/assets/8db08161-7a34-49c2-bb83-c39206064bc8)
I really need this css effect in my project.

**Comment by KurtGokhan** [comment]
`backdrop-filter` isn't supported in ReactUnity. It is too difficult to support in Unity's UGUI system. There are [some ways](https://discussions.unity.com/t/blur-background/792124) but I am not planning to add it for now.

I will check the issue with the box shadow.

**Comment by ds199895** [comment]
> `backdrop-filter` isn't supported in ReactUnity. It is too difficult to support in Unity's UGUI system. There are [some ways](https://discussions.unity.com/t/blur-background/792124) but I am not planning to add it for now.
> 
> I will check the issue with the box shadow.

Thank you very mush for your reply.

**Comment by KurtGokhan** [comment]
The shadow is now culled by the element's own body.

![image](https://github.com/user-attachments/assets/4e855fd3-abb4-4d40-9eca-93d74a18c172)

Also implemented `backdrop-filter` property.

![image](https://github.com/user-attachments/assets/977721d8-50ca-4530-ae87-21807898fa55)

It works almost like browser's implementation ([MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/backdrop-filter)) with the exception that `url` and `drop-shadow` doesn't work. Added two new functions though, those are e.g. `pixelate(10px)` and `grain(30%)`.

Will be available in 0.19.3

**Comment by KurtGokhan** [comment]
[Added to docs](http://localhost:3000/reference/css/backdrop-filter). Closing this.

![image](https://github.com/user-attachments/assets/00208df4-4697-41c8-ad82-b444ba4d2505)
