### ISSUE TITLE
Individual properties of `motion` property don't work correctly 

### ISSUE THREAD

**Issue by gusCreator** [ReactUnity/core#120]
I was trying to create utilities in tailwind for motion individual properties and these don't have effects. I have tried on ![preview docs page](https://reactunity.github.io/reference/animations/motion) and it happens the same.
**This works**:
![imagen](https://github.com/user-attachments/assets/eb4bd2e7-4ce3-462a-bc7e-a992cd77948a)
**This not works**:
![imagen](https://github.com/user-attachments/assets/3eec582b-17f1-4882-9962-ef596301145c)

**Comment by KurtGokhan** [comment]
Fixed in v0.19.6.
