### ISSUE TITLE
Add searchParams to URL and create URLSearchParams

### ISSUE THREAD

**Issue by gusCreator** [ReactUnity/core#121]
I have been trying to add supabase package in my reactUnity project. Their packages use `searchParams` property of `URL` objects but this property is not in ReactUnity. For now, I have had patches in supabase packages to adjust. I think that this property could be added with a `URLSearchParams` class.

**Comment by KurtGokhan** [comment]
Added in 0.19.7

**Comment by gusCreator** [comment]
Hello Kurt! You are so fast, thanks for the feature. I have some problems yet. The method `forEach` does not exist in the implementation. I saw the guide that you followed for the implementation and it does not include this method. But I think that some packages could use it. ![Here](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/forEach) the `forEach` method for `URLSearchParams` by MDN.
