### ISSUE TITLE
forEach method for URLSearchParams

### ISSUE THREAD

**Issue by gusCreator** [ReactUnity/core#122]
Hello Kurt! You are so fast, thanks for the feature. I have some problems yet. The method `forEach` does not exist in the implementation. I saw the guide that you followed for the implementation and it does not include this method. But I think that some packages could use it. ![Here](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/forEach) the `forEach` method for `URLSearchParams` by MDN.

_Originally posted by @gusCreator in https://github.com/ReactUnity/core/issues/121#issuecomment-2480918344_

**Comment by KurtGokhan** [comment]
Done in 0.19.9

**Comment by gusCreator** [comment]
Thank you Kurt. My last problem with this (I hope) is the constructor with an object, key value pair. I think that with this enhancement, compatibility was fulled with `URLSearchParams`

**Comment by gusCreator** [comment]
Ok. I am using a polyfill now. I will wait for the improvement. Thanks!
