### ISSUE TITLE
Inline link support?

### ISSUE THREAD

**Issue by gusCreator** [ReactUnity/core#123]
I have seen that inline text is posible with richtext #25. But this way not supports inline links. Well, there is a way using C# scripts and events but it is very difficult for styling.

**Comment by KurtGokhan** [comment]
There is a sample element in the full-sample repo here: https://github.com/ReactUnity/full-sample/blob/main/react/src/pages/home/index.tsx#L39

You can add an event handler to the `richtext` with `onPointerClick` and navigate to your target based on the clicked link. You have to do styling with the inline tags or `richtext`

**Comment by gusCreator** [comment]
Thanks for the tip!
