### ISSUE TITLE
Cannot load a custom prefab component from Globals?

### ISSUE THREAD

**Issue by gusCreator** [ReactUnity/core#124]
I was trying to load a prefab object with prefab tag in Unity. First, I tried to load from resources with Interop, following [docs](https://reactunity.github.io/reference/components/prefab), but Unity crashes with error `End on file`. Then, I tried to create a custom prefab component dame as the sample. I added it in Globals like a C# script but not works. If I type the extracted object from Globals, an error type raise.

**Comment by gusCreator** [comment]
Update: When I load the component in Globals object. It raises this error: 
```
Unhandled promise rejection: InternalError: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object
  at ReactUnity.UGUI.UGUIComponent.UpdateOrder (System.Int32 prev, System.Int32 current) [0x0019b] in ./Library/PackageCache/com.reactunity.core@0.19.9/Runtime/Frameworks/UGUI/Components/UGUIComponent.cs:651
```
In that [file](https://github.com/ReactUnity/core/blob/main/Runtime/Frameworks/UGUI/Components/UGUIComponent.cs#L651), if the null verification is carried out, it does not show canvas, only UGUI game objects.

**Comment by gusCreator** [comment]
Update: It is possible to set the script during the execution and custom prefab component works. Also, if I change the route (I am using ReactRouter) after the global setting, and back to route that renders prefab component, raises the same error.

**Comment by KurtGokhan** [comment]
I couldn't picture the problem in my head. Can you share part of the code you are having problem with? I will try to check what is wrong during the weekend.

**Comment by gusCreator** [comment]
Okey here is my code. This is my C# script:
```C#
public class MainStar : MonoBehaviour, IPrefabTarget
{
    PrefabComponent Component { get; set; }
    GameObject instance;
    public float rotationSpeed = 3f;
    public Material customMaterial;
    public GameObject prefab;

    public void Mount(PrefabComponent cmp)
    {

        Component = cmp;
        if (prefab != null)
        {
            instance = Instantiate(prefab, Vector3.zero, Quaternion.identity);
            instance.transform.SetParent(cmp.RectTransform, false);
            instance.transform.localScale = new Vector3(250f, 250f, 250f);

            RectTransform rectTransform = instance.GetComponent<RectTransform>();
            if (rectTransform != null)
            {
                rectTransform.anchorMin = new Vector2(0.5f, 0.5f); // Centro
                rectTransform.anchorMax = new Vector2(0.5f, 0.5f); // Centro
                rectTransform.anchoredPosition = Vector2.zero;
            }

            Renderer renderer = instance.GetComponent<Renderer>();
            if (renderer != null)
            {
                if (customMaterial != null)
                {
                    renderer.material = customMaterial;
                    Debug.Log("Material assigned successfully");
                }
            }
            else
            {
                Debug.LogError("No Renderer found on the prefab");
            }
        }
        else
        {
            Debug.LogError("Failed to load prefab");
        }
    }

    public bool SetProperty(string propertyName, object value)
    {
        return false;
    }

    public Action AddEventListener(string eventName, Callback callback)
    {
        return null;
    }

    public void Unmount(PrefabComponent cmp)
    {
        Debug.Log("Unmounting Main Star component");
        Component = null;
    }

    void Update()
    {
        if (instance != null)
        {
            Vector3 inclinedAxis = new Vector3(0.3f, 1f, 0f).normalized;
            instance.transform.Rotate(inclinedAxis, rotationSpeed * Time.deltaTime);
        }

    }
```
I set its values in UnityEditor:
![imagen](https://github.com/user-attachments/assets/8ca62ed3-f683-4ca4-a2ac-19d8e224e215)
This is my component in React. I will only put what is necessary:
```jsx
export default function MainMenu() {
  const { Star } = useGlobals();
  return (
    <view className="flex flex-col flex-auto gap-10 portrait:gap-20">
        <prefab
          className="basis-52 self-center"
          target={Star}
        />
    </view>
  );
}
```
Finally, the error is raised and the game object hierarchy looks like this.
![imagen](https://github.com/user-attachments/assets/79185f62-8493-4a91-acdd-6daecb481eac)
I tried with the sample component showed in the [page](https://reactunity.github.io/reference/components/prefab) but the result is the same.

**Comment by KurtGokhan** [comment]
You shouldn't assign the React Canvas, but the whole GameObject as the prefab. Can you try that?

**Comment by gusCreator** [comment]
Okey, I modified the script:
```C#
public class MainStar : MonoBehaviour, IPrefabTarget
{
    PrefabComponent Component { get; set; }

    public float rotationSpeed = 3f;

    public void Mount(PrefabComponent cmp)
    {
        Component = cmp;

    }

    public bool SetProperty(string propertyName, object value)
    {
        return false;
    }

    public Action AddEventListener(string eventName, Callback callback)
    {
        return null;
    }

    public void Unmount(PrefabComponent cmp)
    {
        Component = null;
    }

    void Update()
    {
        Vector3 inclinedAxis = new Vector3(0.3f, 1f, 0f).normalized;
        transform.Rotate(inclinedAxis, rotationSpeed * Time.deltaTime);

    }
}
```
I instantiated star prefab and I applied the script:

![imagen](https://github.com/user-attachments/assets/1d7cde1e-6eb2-4b7a-8637-4a95c458a0da)
![imagen](https://github.com/user-attachments/assets/439d1337-35b8-4191-a531-8a7f8c91dc13)
Then I added to Globals:
![imagen](https://github.com/user-attachments/assets/e0d619a5-40ce-420c-a49e-4649f38a15c2)
When I start the game, Unity crashes with `End of file` error in log.
```
TcpMessagingSession - receive error
AssetImportWorkerClient::OnTransportError - code=2 error=End of file
```

**Comment by KurtGokhan** [comment]
I don't know that error, but I see there is a misunderstanding. `prefab` doesn't render 3d objects in a 2d UI. It cannot. For that, you may need to set-up another canvas and render it with `<render>` tag. It is kinda an advanced use case but there is an example of it [here](https://github.com/ReactUnity/full-sample/blob/main/react/src/pages/images/index.tsx#L144).

**Comment by gusCreator** [comment]
Okey I understand, I will try to use `<render>` tag. But, as a last doubt, if I set the globals while the game is running using [first way](https://github.com/ReactUnity/core/issues/124#issuecomment-2507694606), the object rendered correctly and I am a little confused about that.

**Comment by KurtGokhan** [comment]
@gusCreator `<prefab>` tag expects a game object with a `RectTransform`. In your first way, you are adding a `Transform` to `RectTransform` as a child. Your way may work for you, and that is ok.

**Comment by gusCreator** [comment]
Okey, thanks for response!
