### ISSUE TITLE
React doesn't reload on globals change

### ISSUE THREAD

**Issue by Gestaltix** [ReactUnity/core#14]
Hi, love this package! It's something I've always wanted for unity. I noticed in my unity project that react doesn't seem to rerender when Globals change. Is this a known issue, or am I doing something wrong? If you'd like, I can bring some further details/images to clarify

**Comment by KurtGokhan** [comment]
Globals are not supposed to change. They are meant to be global constants. They are passed from C# to the React side only at the initialization and never again. What you can do is, you can assign a MonoBehavior to a global, then handle the changes inside that MonoBehavior. You can have an internal dictionary that holds the variables, and add events that handle changes to variables to trigger a render in React side.

Also, ReactUnity does not rerender React components itself. That is handled by React. If you want to rerender a component, you need to do it in React way. You can try one of [these methods](https://dev.to/vaibhavkhulbe/here-s-how-to-force-a-re-render-in-react-6hj).

**Comment by Gestaltix** [comment]
Alright, how would I go about making an event to trigger the react render? I currently have a monobehaviour (assigned as a global), but variables that change within that monobehaviour aren't reflected on the react side of things.

Thanks for the help in advance!

**Comment by caldarellial** [comment]
I've had early luck working with UnityEvents to accomplish this. Hope this helps.

![image](https://user-images.githubusercontent.com/7096661/124616765-5b8c5d00-de44-11eb-95a0-16c5baa51da8.png)
![image](https://user-images.githubusercontent.com/7096661/124616844-6cd56980-de44-11eb-8b58-36d044b089f7.png)

**Comment by KurtGokhan** [comment]
Thanks @caldarellial , good example. 

This seems like a common use case so I will check if it is possible to do the change detection with React Contexts.

**Comment by Gestaltix** [comment]
OH! I didn't know you could add event listeners across the language! That's incredible, thank you so much. This project is great

**Comment by KurtGokhan** [comment]
This is now possible with latest version of `@reactunity/core` and `@reactunity/renderer`.

`reactunity/renderer` now has two useful exports: `GlobalsProvider` component and `useGlobals` hook. Example usage:

```tsx
function App() {
  // This will be rerendered when Globals change in the C# side
  const globals = useGlobals();

  // Component logic here ...
}

Renderer.render(
  <GlobalsProvider>
    <App />
  </GlobalsProvider>
);
```
