### ISSUE TITLE
How to support unity version since 2017

### ISSUE THREAD

**Issue by donadoo** [ReactUnity/core#17]
since unity 2020 is latest, but old project may use 2017 or else, how to support old unity versions?

**Comment by KurtGokhan** [comment]
Supporting multiple Unity versions for multiple platforms is arguably the most time consuming thing in maintaining a Unity package. Thus, I have no plans to support Unity versions before 2020. Unity 2017 is missing a lot of architectural features I am using to make the development easy, such as package manager, assembly definitions, latest C# compiler etc.

What is your use case though? Are you planning to write a new Unity project from scratch or are you trying to mod an existing game?

**Comment by donadoo** [comment]
> Supporting multiple Unity versions for multiple platforms is arguably the most time consuming thing in maintaining a Unity package. Thus, I have no plans to support Unity versions before 2020. Unity 2017 is missing a lot of architectural features I am using to make the development easy, such as package manager, assembly definitions, latest C# compiler etc.
> 
> What is your use case though? Are you planning to write a new Unity project from scratch or are you trying to mod an existing game?

@KurtGokhan I want to trying to add to en existing game which use unity 2017, upgrade to unity 2020 may not possible

**Comment by KurtGokhan** [comment]
ReactUnity supports 2019.4 now. It will be the earliest version that is supported.
