### ISSUE TITLE
load react unity script slow

### ISSUE THREAD

**Issue by donadoo** [ReactUnity/core#18]
load with react unity script(not development build)
https://user-images.githubusercontent.com/44422450/128189662-9c8dce92-0063-478e-989f-ab99b96b19ea.mp4

disable react unity script
https://user-images.githubusercontent.com/44422450/128189948-f91436a4-5a60-4546-85bc-c2c6e3537acd.mp4

is there any settings not correct?

**Comment by KurtGokhan** [comment]
Initial loading in mobile can be slow, as ClearScript is not available in mobile and we need to use Jint engine. Thousands of Javascript code is executed to run React. I am constantly adding new features to ReactUnity but not all of them is optimized for performance yet. There is certainly a room for improvement in CSS and initial element creation.

But a more fair comparison would trying with a UI with similar elements without React part. Loading Unity UI itself can be slow as well.
