### ISSUE TITLE
Image masking

### ISSUE THREAD

**Issue by caldarellial** [ReactUnity/core#19]
Hi, been really enjoying this framework -

Any chance that image masking can make its way onto the roadmap? Would be really helpful for some work I'm doing with health/loading bars, etc with more complex shapes that can't be handled by just the overflow prop, unless there's some way to accomplish this that I've missed.

https://docs.unity3d.com/Packages/com.unity.ugui@1.0/manual/script-Mask.html

**Comment by KurtGokhan** [comment]
Sounds like a good idea. Will work on it.

**Comment by KurtGokhan** [comment]
Added `mask-image` (or `maskImage`) CSS property. Works like `background-image`.

Example: `mask-image: url(resource:images/myMask)`

Right now it takes full size of the element, and you cannot resize or reposition it. In the future it will support most of the [mask spec](https://developer.mozilla.org/en-US/docs/Web/CSS/mask). I need to implement [background spec](https://developer.mozilla.org/en-US/docs/Web/CSS/background) first.
