### ISSUE TITLE
MaxWidth, MaxHeight, MinWidth, MinHeight cannot be set to undefined

### ISSUE THREAD

**Issue by mariuschiriac** [ReactUnity/core#2]
Hi, very good package, I like it.
The react layout props auto value is translated to 0.

example of layout prop added to a button in .tsx:
```
layout:{
    MaxWidth: 'auto',
    MaxHeight: 'auto',
    Width: '50%',
    Height: '10%',
    MinWidth: 10,
    MinHeight: 10
}
```

it will show the buttun 10*10px even if width is 99999px because the MaxWidth value will set the max-width to 0.

I hope to be enough clear.

**Comment by KurtGokhan** [comment]
You can use `null` instead of `'auto'` to overcome this problem.

This is probably a bug with Yoga I noticed before. For MaxWidth etc, the Yoga will convert 'auto' to 0. I don't know why it does that. It cannot be fixed in this package. So please use `null` for this.

**Comment by KurtGokhan** [comment]
I checked it and it is not possible to unset them even when using `null`. I will try to find a way to fix this.

**Comment by KurtGokhan** [comment]
Closing as fixed and covered by tests.
