### ISSUE TITLE
Inline element support?

### ISSUE THREAD

**Issue by amagee** [ReactUnity/core#25]
Is there any support for inline elements?

I would like to render text with various stylings (ie. as if generated from Markdown).

I'd be happy to generate the markup manually, ie. if I wanted to render "regular *italic* regular" I would do something like

```
<span>regular</span>
<span style={{fontStyle: "italic"}}>italic</span>
<span>regular</span>
```

but I'm not sure how to create an equivalent of a span tag or if it is even possible.

**Comment by amagee** [comment]
Update: I have found out that

```
<text>
   {"regular <i>italic</i> regular"}
</text>
```

basically does what I am looking for at the moment.

**Comment by KurtGokhan** [comment]
Inline layout is not possible. ReactUnity has flexbox layout only.

To style text inline, what you did is correct. It is called rich text and it is a feature of TextMesh Pro. [Here](http://digitalnativestudios.com/textmeshpro/docs/rich-text/) is its documentation.

So you can write something like:

```
<text>
  {`<color="red">Red <color=#005500>Dark Green 
<#0000FF>Blue <color=#FF000088>Semitransparent Red`}
</text>

```

**Comment by KurtGokhan** [comment]
Closing this issue. I will document all of this when I have time.
