### ISSUE TITLE
Making Unity call a function on the React side?

### ISSUE THREAD

**Issue by Raicuparta** [ReactUnity/core#31]
Example of what I'm trying to achieve:

```cs
// unity.cs

int counter = 0;
DoThing(Action<int> callback)
{
  counter++;
  callback(counter);
}
```

```tsx
// react.tsx

onClick={() =>
  globals.unity.DoThing((counter: number) => {
    console.log(counter);
  })
}
```
So JS calls the CS method, which in turn calls a JS callback.

Looking at the generated types for `Action`, I'm guessing this isn't how it would work. Any way to achieve something like this? Just want my JavaScript to be able to react to something that happened on the C# side.

**Comment by KurtGokhan** [comment]
Are you trying to pass a Javascript function as argument to C# side? If so ReactUnity has a helper class to do that, which is used internally to handle event callbacks, but is also intended for external usage as well. You can use it like:

```csharp
// unity.cs

int counter = 0;
DoThing(ReactUnity.Helpers.Callback callback)
{
  counter++;
  callback.Call(counter);
}

```

```tsx
//react.tsx

// You should probably memo this for better performance
const callback = Interop.ReactUnity.Helpers.Callback.From((counter: number) => {
    console.log(counter);
});

...
onClick={() =>
  globals.unity.DoThing(callback)
}
```

Note that you should also memo `onClick` function but it is up to you.

**Comment by KurtGokhan** [comment]
Alternatively, you can convert to Callback in C# side:

```csharp
// unity.cs

int counter = 0;

public void DoThing(object cb)
{
  var callback = ReactUnity.Helpers.Callback.From(cb);
  counter++;
  callback.Call(counter);
}

```

```tsx
// react.tsx

onClick={() =>
  globals.unity.DoThing((counter: number) => {
    console.log(counter);
  })
}
```

**Comment by Raicuparta** [comment]
Yes, exactly what I needed. I actually just came back here to say I figured out that using `ScriptObject` worked, but that helper method seems better. Thanks!

Just for reference, this is what I was doing:
```cs
public void DoThing(ScriptObject callback)
{
  counter++;
  callback.Invoke(false, counter);
}
```

As for your memo remark: I'm quite comfortable with React, and I usually wouldn't memoize callbacks unless I need to optimize that specific component. The React docs agree with this, and so do the people who made React. Is there some reason specific to ReactUnity that means I should be memoizing more stuff than usual?

**Comment by KurtGokhan** [comment]
Yep, `ScriptObject` will also work, but it is specific to one engine (either Jint or ClearScript). `Callback` should be able to handle all existing (and future) Javascript engines ReactUnity supports.

**Comment by KurtGokhan** [comment]
Thanks for clarifying. I mention some React tips from time to time because I guess most people using Unity won't know how to use React well. It is all ok if you know what you are doing.

**Comment by Raicuparta** [comment]
Ah you're too fast. I deleted my remark about memo because I realized you suggested it due to `Helpers.Callback.From()`, I'm guessing that's the part that can be slow. In which case the suggestion makes sense. Thanks again!
