### ISSUE TITLE
CSS font-family doesn’t tolerate quotation marks

### ISSUE THREAD

**Issue by aaptho** [ReactUnity/core#34]
In my project, I’m using a custom font family, specified using `@font-face`

When using this font-family in a class, I found that it doesn't work if I have quotation marks around the font-family value. Removing the quotation marks lets it work.

CSS on web tolerates quotes around the font-family value, so I think ReactUnity should allow with or without quotes as well.

```
@font-face {
  font-family: "SofiaProBold";
  src: url("resource:FontsAndMaterials/SofiaProBold");
}

.title {
  font-family: "SofiaProBold"; // <-- this does not work
  font-family: SofiaProBold; // <-- this works
}
```

**Comment by KurtGokhan** [comment]
Fixed in 0.8.2. 

Covered by tests: https://github.com/ReactUnity/core/blob/main/Tests/Runtime/Styles/FontTests.cs#L21
