### ISSUE TITLE
CSS selector support request: text-transform

### ISSUE THREAD

**Issue by aaptho** [ReactUnity/core#35]
TextMeshPro labels support lowercase, uppercase, and small caps transforms via the `FontStyles` property, but these don’t seem to be plumbed through in ReactUnity.

It would be great to have the CSS `text-transform` selector apply those style values to TextMesh Pro instances.

**Comment by KurtGokhan** [comment]
This is currently supported with `font-style` CSS property. Can define multiple styles separated by comma. Example:

```
font-style: italic, uppercase;
```

It is non-standard, so `text-transform` needs to be implemented in the future.

**Comment by KurtGokhan** [comment]
Added in 0.9.0
