### ISSUE TITLE
Immer patch doesn’t resolve when using Jint

### ISSUE THREAD

**Issue by aaptho** [ReactUnity/core#37]
After switching from ClearScript to Jint, our Immer state patching gives this error. I verified that the path in question does indeed exist. What else can I provide to help debug?

The path structure in question:
`rooms: { [key: string]: RoomData }`

```
[Immer] Cannot apply patch, path doesn't resolve: rooms/6164fb93609d220001cf6adc
   at beginWork$1 (current, unitOfWork, lanes) :16340:13
   at performUnitOfWork (unitOfWork) :15167:16
   at workLoopSync () :15101:9
   at renderRootSync (root, lanes) :15067:11
   at bound performSyncWorkOnRoot :14650:22
   at eventHandler () :2556:30
   at unstable_runWithPriority (priorityLevel, eventHandler) :468:16
   at runWithPriority (reactPriorityLevel, fn) :2502:14
   at flushSyncCallbackQueueImpl () :2551:13
   at flushSyncCallbackQueue () :2539:7
   at scheduleUpdateOnFiber (fiber, lane, eventTime) :14250:13
   at bound dispatchAction :7493:9
   at :52:9
```

**Comment by KurtGokhan** [comment]
Can you give an example of what operations are you doing?

**Comment by aaptho** [comment]
`{"op": “add", “value": { … } }`

It looks like the first patch it fails on is giant (> 16384 characters of JSON), so is it possible it’s a size issue?

**Comment by KurtGokhan** [comment]
I could not reproduce this no matter what I did. For me to solve this, you can either send me the JSON of state and the patch at the time of error. 

Is it possible that some C# objects are mixed in with your state? I imagine this error could happen then.

**Comment by lourd** [comment]
Here's a narrow reproduction:

```ts
import { Renderer } from "@reactunity/renderer"
import { applyPatches, enablePatches, Patch } from "immer"
import { useEffect } from "react"

// Required for being able to apply patches to the state
enablePatches()

function Root() {
  useEffect(() => {
    const state = { rooms: {} }
    const patches: Patch[] = [
      {
        op: "add",
        value: {
          foo: "bar",
        },
        path: ["rooms", "abc"],
      },
    ]

    const newState = applyPatches(state, patches)
    console.log("new state")
    console.log(JSON.stringify(newState, null, 2))
  }, [])

  return <view />
}

Renderer.render(<Root />)
```

That component throws an exception with `[Immer] Cannot apply patch, path doesn't resolve: rooms/abc`. Trying that same snippet in the browser works fine (see [this Codesandbox](https://codesandbox.io/s/cranky-brattain-xj504?file=/src/index.ts:0-309)), with the resulting state being `{ rooms: { abc: { foo: 'bar' }}}`

**Comment by KurtGokhan** [comment]
I can confirm that the issue exists in 0.9.0 but not in 0.9.1. Jint was updated between these versions and this issue might have been fixed then. Please reopen if you still experience this issue after updating.

**Comment by lourd** [comment]
Thanks for taking a look so quickly!

After upgrading to 0.9.1 I get a compile error about multiple precompiled assemblies with the same name.

```
Multiple precompiled assemblies with the same name System.Memory.dll included or the current platform. Only one assembly with the same name is allowed per platform. (/Users/...MyUnityProject/Library/PackageCache/com.reactunity.core@1ae73c8212/Plugins/Jint/System.Memory.dll)
Multiple precompiled assemblies with the same name System.Memory.dll included or the current platform. Only one assembly with the same name is allowed per platform. (Assets/Packages/System.Memory.dll)
```

If I go in and delete the `System.Memory.dll` file from the `Jint` directory, I get another error, this time about `System.Runtime.CompilerServices.Unsafe.dll`.

I also tried deleting the entiry `PackageCache` folder and `ScriptAssemblies` folder under `Library` and let Unity regenerate them — that did not solve the problem.

I'm using Unity 2020.3.19f1.

**Comment by KurtGokhan** [comment]
@lourd  do you use another library that imports `System.Memory.dll` or added this file yourself? (into `Assets/Packages` as it seems)

**Comment by KurtGokhan** [comment]
Can you try with 0.9.2. I think that should solve the issue for now.

**Comment by lourd** [comment]
That did the trick, thank you @KurtGokhan!!
