### ISSUE TITLE
<input> placeholder prop doesn’t yield placeholder

### ISSUE THREAD

**Issue by aaptho** [ReactUnity/core#38]
This markup
`<input placeholder=“Input placeholder” />`
results in a text field with no placeholder visible; here’s a screenshot of the editor UI
![image](https://user-images.githubusercontent.com/6288076/150249070-a2d81da5-2c79-4f0a-8729-915b64bd0b4c.png)

There isn’t any placeholder in the hierarchy AFAICT.
The placeholder prop of `<TextField>` is working as expected

Reproduces 100% in the ReactUnityFullSample project

**Comment by KurtGokhan** [comment]
Should be fixed in 0.9.1. Also, placeholder can be styled with `::placeholder` CSS selector.
