### ISSUE TITLE
Material icons disappear on re-render

### ISSUE THREAD

**Issue by Syynth** [ReactUnity/core#39]
Minimal reproduction
https://github.com/Syynth/reactunity-icon-bug

```typescript
import { Renderer } from '@reactunity/renderer';
import { useState } from 'react';
import './index.scss';

function App() {
  const [count, setCount] = useState(0);
  return <icon onPointerClick={() => setCount(count + 1)}>house</icon>;
}

Renderer.render(<App />);
```

Depending on the icon, in Unity I can see some text in the TMP component inspector, and after clicking the icon, that text has been cleared.

**Comment by KurtGokhan** [comment]
Fixed in `@reactunity/renderer` version 0.9.2.
