### ISSUE TITLE
Shorthand properties for border-bottom and border-right don't accept color

### ISSUE THREAD

**Issue by bcochranemax** [ReactUnity/core#40]
When using the `border-bottom` and `border-right` shorthand css syntax, color is ignored unless set separately. They do work if used in conjunction with another `border-*` property, or with `border-color`, but not on their own.

Here is a visual representation of how they function. 
![unknown](https://user-images.githubusercontent.com/95254999/161276907-28044e63-aa42-4893-9f71-060b76a83927.png)

```typescript
// does not set color
<view style={{ borderBottom: '2px solid green' }} />
<view style={{ borderRight: '2px solid green' }} />
// sets color correctly
<view style={{ borderColor: 'green', borderBottom: '2px solid' }} />
<view style={{ borderBottom: '2px solid green', borderRight: '2px solid green' }} />
<view style={{ borderBottom: '2px solid green', borderTop: '2px solid green' }} />
```

**Comment by KurtGokhan** [comment]
Fixed in core@0.9.4

A bug in border shader caused it to pick top's color for bottom and left's color for right in certain situations.
