### ISSUE TITLE
UnityEngine.InputSystem not found

### ISSUE THREAD

**Issue by Muchaszewski** [ReactUnity/core#43]
When importing a package from the source, instead of a package, because tests are using a new input system, a pre-processor is needed. Otherwise, the project cannot be properly imported while using the old input system.

Example exception:
```
Packages\react-unity-core\Tests\Runtime\Utils\TestBase.cs(27,17): error CS0246: The type or namespace name 'Mouse' could not be found (are you missing a using directive or an assembly reference?)
```

Because adding preprocessors to whole test classes creates other issues, I propose adding "Define Constraints" to the asmdef of the tests files.

Is: `UNITY_INCLUDE_TESTS`
Should be `UNITY_INCLUDE_TESTS && ENABLE_INPUT_SYSTEM` 
![image](https://user-images.githubusercontent.com/5092066/164988846-bc9dc097-1791-4c3e-849d-0387c7d98a0d.png)

**Comment by KurtGokhan** [comment]
Hmm, I thought Unity wouldn't include test assembly for packages unless they were in `testables`. Is this happening because you added `com.reactunity.core` to `testables`?

**Comment by Muchaszewski** [comment]
Nope, here is what I did.

1. Create new project
2. Into Packages folder clone https://github.com/ReactUnity/core from main
3. In Package Manager import this package from file
4. Notice exceptions due to missing packages

**Comment by KurtGokhan** [comment]
Ok, added check for it. Changes are on main branch.
