### ISSUE TITLE
Not all transition css properties are working

### ISSUE THREAD

**Issue by Muchaszewski** [ReactUnity/core#47]
When creating transition we might want to split the `transition` CSS property into multiple properties like: `transition-property`, `transition-duration`, `transition-delay`.

As from examples: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Transitions/Using_CSS_transitions#simple_example

Currently, they are not working

**Working code**
```
.transition {
    transition: opacity cubic-bezier(0.4, 0, 0.2, 1) 300ms;
}
```

**Not working equivalent**
```
.transition-test {
    transition-property: opacity;
    transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
    transition-duration: 300ms;
}
```

Other issues that's are caused by the same root cause.

**Property split between styles**
```
.transition {
    transition: opacity cubic-bezier(0.4, 0, 0.2, 1) 300ms;
}

.transition-longer{
    transition-duration: 1s;
}

<div className="transition transition-longer" ...
```

**Transition "all"**
```
.transition {
    transition-property: color, background-color, border-color, text-decoration-color, fill, stroke, opacity, box-shadow, transform, filter, backdrop-filter;
    transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
    transition-duration: 150ms;
}
```

**Comment by KurtGokhan** [comment]
Should be working now.

**Comment by Muchaszewski** [comment]
It works! This is an extremely fast response time!

With this working, I think the tailwind as a library should be usable to create a proper UI (with small caveats :D )
