### ISSUE TITLE
Multiple websocket-sharp.dll file when using with Photon

### ISSUE THREAD

**Issue by hoonsubin** [ReactUnity/core#52]
When I installed this package on a project that is using Photon, I get the following error as the library also adds the same precompiled assembly:

`Multiple precompiled assemblies with the same name websocket-sharp.dll included on the current platform. Only one assembly with the same name is allowed per platform.`
<img width="1419" alt="Screen Shot 2022-05-06 at 10 23 06 AM" src="https://user-images.githubusercontent.com/40356749/167096199-fc5de70d-0c98-4874-a232-372bfa14a77e.png">

**Comment by KurtGokhan** [comment]
I don't know if there is a legit way to solve this in Unity. The solution I found is too add a precompile directive to exclude the dll from ReactUnity.

So now, if you define `REACT_EXCLUDE_WEBSOCKET_SHARP` in player settings, ReactUnity won't load this dll.

All managed dlls included by ReactUnity can be excluded in a similar manner.
