### ISSUE TITLE
conflicting .js file scripted importer

### ISSUE THREAD

**Issue by hoonsubin** [ReactUnity/core#53]
When I load the ReactUnity package, I get the following error:
```
The scripted importer 'ReactUnityTextAssetsImporter' attempted to register file type '.js', which is handled by a native Unity importer. Registration rejected.
UnityEditor.AssetImporters.ScriptedImporter:RegisterScriptedImporters ()
```
I'm using Unity 2021.2.3f1 and ReactUnity version 0.11.1.

**Comment by KurtGokhan** [comment]
This is a problem caused by a breaking change in Unity 2021.2 and 2021.3 versions. I recommend upgrading to latest version of those. 

If you don't want to upgrade, this warning will not cause any problems.
