### ISSUE TITLE
Scroll position resetting after clicking input

### ISSUE THREAD

**Issue by noah-potter** [ReactUnity/core#68]
I'm seeing a bug where the scroll position resets when clicking inputs. I recreated this with the latest ReactUnity/full-sample by running the UIToolkit scene without any changes, scrolling down to an input, and clicking several times (in my project it happens more frequently often on the first click)

Unity version: 2021.3.8f1

https://user-images.githubusercontent.com/17100846/198515844-33e9ac95-796c-47c0-9d46-cca362959f2e.mp4

**Comment by KurtGokhan** [comment]
I noticed it is not clicking that causes this behavior. It is caused by dragging. I will try to see why it happens.

**Comment by noah-potter** [comment]
Oh nice, thanks! I'll close this now since it isn't related to this project
