### ISSUE TITLE
console.log only shows the first parameter

### ISSUE THREAD

**Issue by openefit** [ReactUnity/core#69]
console.log with multi parameters only shows the first
``` javascript
console.log('first', 'NEVER SHOWS') //=> first
```
an alternative way is to use Template literals
``` javascript
console.log(`this works, 1 + 1 = ${1 + 1}`)  //=> this works, 1 + 1 = 2
```

**Comment by KurtGokhan** [comment]
Added a basic solution in v0.14.0. Full console spec may be implemented in future versions. https://console.spec.whatwg.org/
