### ISSUE TITLE
Cannot find file in StartWithShellExecuteEx

### ISSUE THREAD

**Issue by nicbarker** [ReactUnity/core#7]
Great idea for a project, awesome work!
When I run this on 2019.3 on mac os X, I get the following error when clicking on "create project" in the editor:
<img width="752" alt="Screenshot 2020-07-25 17 22 34" src="https://user-images.githubusercontent.com/2264338/88449507-8b448e00-ce9b-11ea-815f-10177d8aeedf.png">
<img width="853" alt="Screenshot 2020-07-25 17 22 29" src="https://user-images.githubusercontent.com/2264338/88449529-c1820d80-ce9b-11ea-9e26-59f983a79419.png">

**Comment by KurtGokhan** [comment]
Unfortunately, if Quick Start menu does not work for you, you will have to do it manually. I cannot do cross-platform tests yet.

You can do it manually by:

- Install [Node.js](https://nodejs.org/en/) 12
- Go to `/Users/nicbarker/Documents/Test React Project`
- Run `npm init react-unity` from this directory

This will create a react project under `react` folder in this directory. That is everything the Quick Start menu does.

After creating the react project, you can go to `react` folder to run `npm start` and you will be able to start using React Unity right away.

**Comment by nicbarker** [comment]
Hey @KurtGokhan thanks for the quick response! I'll take a look - if you want I can help you out with mac os X tests.

**Comment by KurtGokhan** [comment]
Thanks @nicbarker . Right now the Quick Start wizard is the only place I rely on the OS. And I am actually planning to remove it in favor of [create-react-unity](https://github.com/KurtGokhan/create-react-unity). 

That being said, I never confirmed that React Unity works in Mac OS. Thanks to #5 I know it works for iOS.

**Comment by nicbarker** [comment]
Sounds good, I'll investigate a bit more on OS X and get back to you.

**Comment by KurtGokhan** [comment]
Closing as the quick start window was improved and osx seems to work correctly now.
