### ISSUE TITLE
[UGUI] Text scaling with `rem` is not the same as in web browsers

### ISSUE THREAD

**Issue by Muchaszewski** [ReactUnity/core#70]
The rem scaling is not as in the web browsers. Generally, the text is too big in ReactUnity.

I will discuss the following text with the only variable as font-size.
```
<span style="font-size: medium;">Go to src/index.tsx to edit this file</span>
```

font-size: medium is computed as 1rem which is equal to 16px.

In ReactUnity while using UGUI it's computed as 24px which is too big compared to Chrome.
![image](https://user-images.githubusercontent.com/5092066/203512279-16ce4a94-238c-47dc-ab0b-767b75b76701.png)

When manually changed to proper 16px they look almost identical.
![image](https://user-images.githubusercontent.com/5092066/203512491-72de3603-4b43-4205-8e95-cf68368a62bd.png)

**Comment by Muchaszewski** [comment]
Additional information:
- **em Unit:** The em unit allows setting the font size of an element relative to the font size of its parent. When the size of the parent element changes, the size of the child changes automatically.
- **rem Unit:** The rem is based upon the font-size value of the root element, which is the <html> element. And if the <html> element doesn’t have a specified font-size, the browser default value of 16px is used. So here only the value of the root is considered, and there is no relation with a parent element.

as for the reactUnity example, no CSS style or root of HTML has been changed

**Comment by KurtGokhan** [comment]
The cause of this is simple, root font size is defined as 24px in ReactUnity instead of browser's 16px. This was done with the thought that games usually require bigger fonts.

The font size is defined in useragent stylesheet. It can be easily overridden with:

```css
:root {
  font-size: 16px;
}
```

When we add a useragent stylesheet for browser rendering compatibility, this should be easy to fix.

**Comment by KurtGokhan** [comment]
Changed default font size to 16px in v0.14.0
