### ISSUE TITLE
ReactUnity polyfils are not loaded from Resources

### ISSUE THREAD

**Issue by Muchaszewski** [ReactUnity/core#73]
Unity in version 2020.3.33 is unable to load `js` files from polyfills, as they are just not found. Unity `Resources` class cannot find them as valid extensions.

To fix that I needed to manually copy the files and change the extensions of those files to txt.

![image](https://user-images.githubusercontent.com/5092066/204345813-23dfe27f-7e4a-465f-acf7-923cbf7e74b6.png)

For compatibility reasons, I would keep them as txt in the final package. Either by making them permanently txt or by adding CI pipeline to that to retain the highlights in vscode and others.

**Comment by KurtGokhan** [comment]
If Unity can't find `.js` files in Resources, that will be a problem not only for polyfills, but also for other cases too (after build for example). I don't remember this issue in any unity versions. Might be a bug in Unity 2020.3.33. I will need to investigate.

**Comment by Muchaszewski** [comment]
You are right and I'm dumb :| This is not an issue in 2020 but in 2022.2.0b15. Just double-checked. 

You might be right as this can by only unity version thing

**Comment by KurtGokhan** [comment]
I have encountered similar bugs in Unity beta versions. Thanks for reminding though. 2022.2 will be added to tests in CI once it is released.

**Comment by KurtGokhan** [comment]
Fixed in v0.14.0
