### ISSUE TITLE
[UGUI] Performance Improvement to not create GameObjects that are empty

### ISSUE THREAD

**Issue by Muchaszewski** [ReactUnity/core#77]
If a component does not have anything, do not spawn it. Eg: [Shadows] or [BorderImage].
It should improve reload/update speed significantly. 
![image](https://user-images.githubusercontent.com/5092066/205141489-366479bc-f42a-4fe4-81c2-37f7594f4b9d.png)

The rate at which new GameObjects are added is connected directly to the about of said game objects on the scene and their hierarchy.
From my tests in the past, creating a Single "Empty Object" on a scene with **2500 objects can be around 1-2ms** on a mid-low end PC (slower on mobile). Adding MonoBehaviour has a similar performance effect but 1/4 the penalty. 

This can be part of Pooling behavior, to not spawn objects when they would be needed they can should be quickly taken from a pool. But be aware, that changing the rendering order (enable/disable GO included) forces Canvas to re-render the whole path to the next Canvas.

![image](https://user-images.githubusercontent.com/5092066/205142791-e1ad43c0-da51-473d-8d92-fc4decc3f95e.png)
![image](https://user-images.githubusercontent.com/5092066/205142818-fca4771a-861a-4361-87dd-4fdd2c99bb3d.png)

**Comment by KurtGokhan** [comment]
Improved in v0.14.0
