### ISSUE TITLE
Cannot find ReactUnity component

### ISSUE THREAD

**Issue by wilkesreid** [ReactUnity/core#8]
Whether searching for the ReactUnity component:

![image](https://user-images.githubusercontent.com/509805/90167060-caf6eb00-dd60-11ea-8704-a481ba87e90e.png)

Or using the ReactCanvas prefab:

![image](https://user-images.githubusercontent.com/509805/90166974-a733a500-dd60-11ea-8b73-4e427bca58ce.png)

It seems that after running `openupm add com.reactunity.core`, that component script is not present or cannot be found. I am running Node 12 and Unity 2019.4.8f1. I know this version of Unity is not one of the ones listed as having been tested, so if that's the issue, that's fine. I just want to double check to see whether there's something else going on.

**Comment by KurtGokhan** [comment]
Seems like TextMesh Pro 3.x was not compatible with 2019.4. This caused build to fail and you had compile errors. Anyway, I removed TMP dependency from ReactUnity in v0.0.14 so you can install any version of TMP that is compatible with the Unity version you are using. With Unity 2019.x you need to install TMP 2.x (e.g. 2.1.1).

**Comment by wilkesreid** [comment]
Thanks!
