### ISSUE TITLE
Image Quality/Resolution

### ISSUE THREAD

**Issue by Carln02** [ReactUnity/core#81]
Hello!
I started checking out your library recently and I encountered a small issue with images. Both non-rectangular PNGs and SVGs appear pixelated and low resolution, no matter how high the original resolution of the image is. Below you can find a screenshot of what I'm talking about. The star's image file is a 1028 by 1028px PNG.

<img width="417" alt="Screenshot 2023-01-21 143724" src="https://user-images.githubusercontent.com/98150465/213867167-42a028f8-f662-49dc-bd24-3b0c808c99d0.png">

Thank you!!

**Comment by KurtGokhan** [comment]
Can you provide the following information?

- What is the React code used to generate this behavior?
- How are you providing the image source? If it is an asset inside Unity, what are your import settings? Can you send that asset and its `.meta` file? (Some compression, mipmap or filter mode settings can cause this behavior)
- Does this happen without ReactUnity? Can you try creating a simple UGUI image and try to reproduce it?

**Comment by Carln02** [comment]
1. The code is quite long, but if I run the following in the index file:

`import picture from "src/assets/icons/--primary-main/star-filled.png";
export function App() {
   return (<image source={picture} style={{width: '100px', height: '100px'}}/>);
}
Renderer.render(<App />);`

I get the same pixelated output:
<img width="56" alt="Screenshot 2023-01-21 173225" src="https://user-images.githubusercontent.com/98150465/213874156-9dcee1f0-9029-4bed-8dd0-c3ee19fe69d4.png">

2. Can I access images from the "Assets" folder? Whenever I try to input a path that goes outside the "src" folder in the react project I get an error. The image is placed inside this src folder and it doesn't have a `.meta` file.

Here is the asset:
![star-filled](https://user-images.githubusercontent.com/98150465/213874266-ff99b02a-b89c-43de-b09d-73645f0b0abf.png)

3. If I place the same image as a 2D sprite in Unity it looks perfectly fine.

And thank you so much for the help!

**Comment by KurtGokhan** [comment]
I see. Image imports from file are imported with some default settings. I changed those settings to maximize quality now. 

Fixed on main branch. I won't release a new version urgently as the problem only exists in development. In build, you have to go to the build folder and modify image import settings manually anyway.

**Comment by Carln02** [comment]
Oh okay great!! Thank you for your help :)

**Comment by KurtGokhan** [comment]
Forgot to update, this is already fixed in 0.14.2
