### ISSUE TITLE
Auto-Reload after changes in code are not reflected or automaticaly updated.

### ISSUE THREAD

**Issue by Muchaszewski** [ReactUnity/core#84]
Changes to React project code are not automaticaly updated when changes to the code are made.

**Expected behaviour:**
ReactUI should automatically update when dev-server detects changes

**Current behavior:**
Nothing happens

**Possible workaround**
After each change, you can use the Restart function in ReactUIDocument to update it manually, or you can restart game.

**Other considerations**
 - Maybe it would be useful to add Key-Bind that would work during play mode to reload the UI eg: Ctrl+Shift+R
 - UI Toolbar button or in Scene view a button to do that.
 Both would reduce the amounts of click and a hassle to find proper ReactUI Component in the hierarchy

**Comment by KurtGokhan** [comment]
ReactUnity already supports HMR. It was not working because of a bug that was introduced in 0.14.3 with a change in `location`. Reverted now. Fixed in 0.14.5.

Other solutions you proposed may be added in the future with a comprehensive dev tools implementation.
