### ISSUE TITLE
Chinese didn't render in ReactUnity canvas

### ISSUE THREAD

**Issue by lwyj123** [ReactUnity/core#87]
## Problem
ReactUnity canvas can't render non-latin character like chinese
![image](https://user-images.githubusercontent.com/9214496/226173398-962417a6-9363-4cbc-b0f8-b5304eddc0a2.png)
![image](https://user-images.githubusercontent.com/9214496/226173402-050a94d5-2723-42e8-8383-38df99a311a8.png)

After checking the samples and tests I found a way to use @font-face but it doesn't work.
<img width="835" alt="image" src="https://user-images.githubusercontent.com/9214496/226173534-2f82e93d-d3eb-46e8-8a95-1f3c8fa31c66.png">
![image](https://user-images.githubusercontent.com/9214496/226173555-713f8b74-3d0a-4659-877a-a649768e1562.png)

**Comment by KurtGokhan** [comment]
ReactUnity uses TextMeshPro, so your fond must be converted to a font atlas. You can use Font Asset Creator of TMPro.

![image](https://user-images.githubusercontent.com/6034931/226174838-4d8d1ed2-6480-4243-a50f-00dd155d36be.png)

I don't know the nuances of Chinese fonts, but this should work. You may have to consult a more experienced person for this though.

The character list I used is this, but you can add more characters:

```
0D,20-7E,A0,F6,130-131,200B,2026,4E00-9FFF
```

Also you may want to change Atlas Resolution if fonts seem low resolution.

Let me know if this works.

**Comment by KurtGokhan** [comment]
There is now a docs page for a small guide to add custom fonts. https://reactunity.github.io/learn/howto/fonts
