### ISSUE TITLE
Hide unity loading in the background

### ISSUE THREAD

**Issue by kobechenyang** [ReactUnity/core#9]
Great project ! Is it possible to hide the loading bar and unity loading in the background by displaying any react page in front? If so, how can I do it? Thanks !

**Comment by KurtGokhan** [comment]
This project is for building UI inside Unity. Also this project is not exclusive to WebGL. So your question is out of scope of this project.

You can use this project to have more control over Unity WebGL context: https://github.com/elraccoone/react-unity-webgl
By using events, you should be able to achieve what you want.
