### ISSUE TITLE
compare with react-unity-webgl

### ISSUE THREAD

**Issue by j209** [ReactUnity/core#91]
What are differences and probably advantages this library to [React-Unity-Webgl](https://github.com/jeffreylanters/react-unity-webgl)?

**Comment by KurtGokhan** [comment]
React Unity WebGL is for embedding and controlling an Unity project built for WebGL in React projects.

This project is for building UI inside Unity using React. It doesn't have much common points with React Unity WebGL. This is a framework for Unity, whereas the other package is a package for React. Also this project works for all platforms Unity builds to.
