### ISSUE TITLE
TypeScript is missing the definition of `direction` prop in `scroll` element

### ISSUE THREAD

**Issue by xiaohai-huang** [ReactUnity/core#92]
![image](https://github.com/ReactUnity/core/assets/56380096/5dd2fc1a-88d3-463e-9e13-a2ad787fc330)

![image](https://github.com/ReactUnity/core/assets/56380096/aa4b53cc-090d-45f5-90b1-6af538e56329)

![image](https://github.com/ReactUnity/core/assets/56380096/7d335424-cd18-456a-81df-d39ede09b95e)

**Comment by KurtGokhan** [comment]
Fixed in renderer package version 0.16.2
