### ISSUE TITLE
UI Toolkit renderer is missing css properties like `background-size`

### ISSUE THREAD

**Issue by xiaohai-huang** [ReactUnity/core#93]
![image](https://github.com/ReactUnity/core/assets/56380096/13a267d5-31e7-4974-aa90-b3fc883dc999)

UI Toolkit does support these properties. But I cannot use them in ReactUnity

![image](https://github.com/ReactUnity/core/assets/56380096/69c4a2b2-c249-46fa-a168-95e50d4ea95a)

**Comment by KurtGokhan** [comment]
These must have been added in recent Unity versions. I will add them.

**Comment by xiaohai-huang** [comment]
`object-fit`, `background-*`, `word-spacing` and `letter-spacing` property support is added in 0.16.3
