### ISSUE TITLE
BUG [TypeScript] `UnityEngine.Networking` has no exported member `UnityWebRequest`

### ISSUE THREAD

**Issue by xiaohai-huang** [ReactUnity/core#94]
With the following script. Click "Generate Project TypeScript Models" using the menu. A ts error occurs.

```csharp
public class MyBehavior : MonoBehavior
{
    public UnityEvent<UnityWebRequest> OnStartDownload;

}
```

```
react/node_modules/@reactunity/renderer/dist/src/models/generated/unity".UnityEngine.Networking' has no exported member 'UnityWebRequest'.
    811 |   hideFlags: UnityEngine.HideFlags;
    812 |   UpdateServer: string;
  > 813 |   OnStartDownload: UnityEngine.Events.UnityEvent<UnityEngine.Networking.UnityWebRequest>;
```

**Comment by KurtGokhan** [comment]
Added this and bunch of other types in `@reactunity/renderer@0.16.4`. 

But the TS generator doesn't include all types, so this may happen for some other type in the future. In that case, you have some options:

- Open a Github issue and ask me to add those types
- Manually convert problematic types to `any` after running TS generator
- Add `[TypescriptExclude]` attribute to exclude them from TS generator, or use `[TypescriptRemap]` to convert them to other types
