### ISSUE TITLE
Hot reloading?

### ISSUE THREAD

**Issue by mikecann** [ReactUnity/core#95]
Hey,

This is an awesome project! 

Im just wondering what the status of hot reloading is? I saw the old issue (from 2021) but im not sure if thats up to date.

I downloaded the sample: https://github.com/ReactUnity/full-sample and ran it as per the instructions.

Made some changes to the index.tsx in src/pages/home/index.tsx but I dont see any change unless I stop and play in Unity again.

Any thoughts?

**Comment by mikecann** [comment]
I noticed if I disable then re-enable the canvas at runtime then it also refreshes it..

https://github.com/ReactUnity/core/assets/215033/de4dc8c6-adbd-433e-9d06-345b18b05555

**Comment by KurtGokhan** [comment]
Do you see anything in the Unity console? It seems like it should be working

**Comment by KurtGokhan** [comment]
This was an issue with richtext tags. They were not being updated when updated with HMR. Fixed in new renderer version.
